name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip project files
        run: zip -r app.zip .

      - name: Decode Google Cloud key
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > ${{ github.workspace }}/gcloud.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ github.workspace }}/gcloud.json
          project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT }}

      - name: Upload to Google Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: app.zip
          destination: gs://${{ secrets.GOOGLE_CLOUD_BUCKET }}/app.zip

      - name: Deploy to Google App Engine
        run: gcloud app deploy --quiet
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud.json
